version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
    schedule:
      interval: "weekly"

    groups:
      "catch-all-security-alerts":
        applies-to: "security-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"